# https://mmistakes.github.io/minimal-mistakes/docs/configuration/
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
plugins:
- jekyll-include-cache
locale: "en-US"
minimal_mistakes_skin: "default"
title: "James Rowland"
name: "James Rowland"
description: "A blog to capture and share my thoughts."
url: "https://rowland-208.github.io/"
repository: "rowland-208/rowland-208.github.io"
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      enable_copy_code_button: true
      comments: true
      layout: single
      author_profile: true
      share: true
      related: true
comments:
  provider: "giscus"
  giscus:
    repo_id              : "R_kgDOMhoGIA"
    category_name        : "Blog Post Comments"
    category_id          : "DIC_kwDOMhoGIM4ChiUf"
    discussion_term      : "pathname"
    reactions_enabled    : "1"
    theme                : "preferred_color_scheme"
atom_feed:
  hide: true
search: true
lunr:
  search_within_pages: true
author:
  name     : "James Rowland"
  avatar   : "/assets/images/bio-photo.jpg"
  bio      : "AI, physics, astrodynamics, technology."
  location : "North Carolina, USA"
